sudo: required

language: cpp

compiler:
  - g++

services:
  - docker

os:
  - linux
#  - osx

before_install:
# Linux: create Docker image
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ubuntu:16.04 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -it ubuntu bash ; fi

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then ./.integration/travis-install-linux.sh ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then ./.integration/travis-install-osx.sh ; fi

script:
# SimTaDyn unit tests
  - cd tests && make -j4 || exit 1
  - ./build/UnitTest || exit 1
# SimTaDyn executable
  - cd ../src && make -j4 || exit 1
