HEX

: EMPTY-STACK   \ ( ... -- ) EMPTY STACK: HANDLES UNDERFLOWED STACK TOO.
  DEPTH ?DUP IF DUP 0 < IF NEGATE 0 DO 0 LOOP ELSE 0 DO DROP LOOP THEN THEN ;

: DISP-LINE ( TYPE SOURCE TYPE ) . CR ;
: ERROR DISP-LINE EMPTY-STACK ;
: CORRECT-RES ( S" OK RESULT: " ) 1 DISP-LINE ;
: INCORRECT-RES ( S" INCORRECT RESULT: " ) 2 ERROR ;
: WRONG-NUMBER ( S" WRONG NUMBER OF RESULTS: " ) 3 ERROR ;

VARIABLE ACTUAL-DEPTH           \ STACK RECORD
CREATE ACTUAL-RESULTS 20 CELLS ALLOT

: T{     \ ( -- ) SYNTACTIC SUGAR.
   ;

: ->        \ ( ... -- ) RECORD DEPTH AND CONTENT OF STACK.
   DEPTH DUP ACTUAL-DEPTH !     \ RECORD DEPTH
   ?DUP IF              \ IF THERE IS SOMETHING ON STACK
      0 DO ACTUAL-RESULTS I CELLS + ! LOOP \ SAVE THEM
   THEN ;

: }T     \ ( ... -- ) COMPARE STACK (EXPECTED) CONTENTS WITH SAVED
        \ (ACTUAL) CONTENTS.
   DEPTH ACTUAL-DEPTH @ = IF        \ IF DEPTHS MATCH
      DEPTH ?DUP IF         \ IF THERE IS SOMETHING ON THE STACK
         0 DO               \ FOR EACH STACK ITEM
        ACTUAL-RESULTS I CELLS + @  \ COMPARE ACTUAL WITH EXPECTED
        <> IF INCORRECT-RES LEAVE ELSE CORRECT-RES THEN
     LOOP
      THEN
   ELSE                 \ DEPTH MISMATCH
      WRONG-NUMBER
   THEN
;

T{ 1 1 + -> 2 }T
T{ 1 1 + -> 3 }T

BYE
