#ifndef FORTH_PRIMITIVES_HPP_
#  define FORTH_PRIMITIVES_HPP_

// TODO: primitive INCLUDE
enum ForthPrimitives
  {
    // Dummy word and comments
    FORTH_PRIMITIVE_NOP = 0,
    FORTH_PRIMITIVE_LPARENTHESIS,
    FORTH_PRIMITIVE_RPARENTHESIS,
    FORTH_PRIMITIVE_COMMENTARY,

    // Words for definitions
    FORTH_PRIMITIVE_COLON,
    FORTH_PRIMITIVE_SEMICOLON,
    FORTH_PRIMITIVE_CREATE,
    FORTH_PRIMITIVE_DOES,
    FORTH_PRIMITIVE_IMMEDIATE,

    // Dictionnary manipulation
    FORTH_PRIMITIVE_HERE,
    FORTH_PRIMITIVE_ALLOT,
    FORTH_PRIMITIVE_COMMA,
    FORTH_PRIMITIVE_FETCH,
    FORTH_PRIMITIVE_STORE,

    // Words changing IP
    FORTH_PRIMITIVE_EXIT,
    FORTH_PRIMITIVE_BRANCH,
    FORTH_PRIMITIVE_0BRANCH,

    // Return Stack
    FORTH_PRIMITIVE_TO_RSTACK,
    FORTH_PRIMITIVE_FROM_RSTACK,
    FORTH_PRIMITIVE_2TO_RSTACK,
    FORTH_PRIMITIVE_2FROM_RSTACK,

    // cell sizeof
    FORTH_PRIMITIVE_CELL,
    FORTH_PRIMITIVE_CELLS,

    // Literals
    FORTH_PRIMITIVE_LITERAL_16,
    FORTH_PRIMITIVE_LITERAL_32,

    // Arithmetic
    FORTH_PRIMITIVE_ABS,
    FORTH_PRIMITIVE_NEGATE,
    FORTH_PRIMITIVE_MIN,
    FORTH_PRIMITIVE_MAX,
    FORTH_PRIMITIVE_PLUS,
    FORTH_PRIMITIVE_1PLUS,
    FORTH_PRIMITIVE_2PLUS,
    FORTH_PRIMITIVE_MINUS,
    FORTH_PRIMITIVE_1MINUS,
    FORTH_PRIMITIVE_2MINUS,
    FORTH_PRIMITIVE_TIMES,
    FORTH_PRIMITIVE_DIV,
    FORTH_PRIMITIVE_RSHIFT,
    FORTH_PRIMITIVE_LSHIFT,

    // Logic
    FORTH_PRIMITIVE_GREATER,
    FORTH_PRIMITIVE_GREATER_EQUAL,
    FORTH_PRIMITIVE_LOWER,
    FORTH_PRIMITIVE_LOWER_EQUAL,
    FORTH_PRIMITIVE_EQUAL,
    FORTH_PRIMITIVE_NOT_EQUAL,
    FORTH_PRIMITIVE_AND,
    FORTH_PRIMITIVE_OR,
    FORTH_PRIMITIVE_XOR,

    // Data Stack
    FORTH_PRIMITIVE_DEPTH,
    FORTH_PRIMITIVE_NIP,
    FORTH_PRIMITIVE_PICK,
    FORTH_PRIMITIVE_DUP,
    FORTH_PRIMITIVE_QDUP,
    FORTH_PRIMITIVE_DROP,
    FORTH_PRIMITIVE_SWAP,
    FORTH_PRIMITIVE_OVER,
    FORTH_PRIMITIVE_ROT,
    FORTH_PRIMITIVE_TUK,
    FORTH_PRIMITIVE_2DUP,
    FORTH_PRIMITIVE_2SWAP,
    FORTH_PRIMITIVE_2DROP,
    FORTH_PRIMITIVE_2OVER,

    // Printf
    FORTH_PRIMITIVE_DISP,
    FORTH_PRIMITIVE_CARRIAGE_RETURN,
    NUM_PRIMITIVES
  };

// TODO: ASSERT_COMPILE_TIME(NUM_PRIMITIVES < sizeof (Cell16))

#endif /* FORTH_PRIMITIVES_HPP_ */
