#ifndef FORTH_PRIMITIVES_HPP_
#  define FORTH_PRIMITIVES_HPP_

// TODO: primitive INCLUDE
enum ForthPrimitives
  {
    FORTH_PRIMITIVE_NOP = 0,
    FORTH_PRIMITIVE_LPARENTHESIS,
    FORTH_PRIMITIVE_RPARENTHESIS,
    FORTH_PRIMITIVE_COMMENTARY,

    FORTH_PRIMITIVE_COLON,
    FORTH_PRIMITIVE_EXIT,
    FORTH_PRIMITIVE_SEMICOLON,
    FORTH_PRIMITIVE_LITERAL,

    FORTH_PRIMITIVE_1MINUS,
    FORTH_PRIMITIVE_1PLUS,
    FORTH_PRIMITIVE_2MINUS,
    FORTH_PRIMITIVE_2PLUS,

    FORTH_PRIMITIVE_NIP,
    FORTH_PRIMITIVE_DUP,
    FORTH_PRIMITIVE_DROP,
    FORTH_PRIMITIVE_SWAP,
    FORTH_PRIMITIVE_OVER,
    FORTH_PRIMITIVE_ROT,
    FORTH_PRIMITIVE_TUK,

    FORTH_PRIMITIVE_2DUP,
    FORTH_PRIMITIVE_2OVER,
    FORTH_PRIMITIVE_2SWAP,
    FORTH_PRIMITIVE_2DROP,

    FORTH_PRIMITIVE_PLUS,
    FORTH_PRIMITIVE_MINUS,
    FORTH_PRIMITIVE_DIV,
    FORTH_PRIMITIVE_TIMES,
    FORTH_PRIMITIVE_RSHIFT,
    FORTH_PRIMITIVE_LSHIFT,
    FORTH_PRIMITIVE_GREATER_EQUAL,
    FORTH_PRIMITIVE_LOWER_EQUAL,
    FORTH_PRIMITIVE_GREATER,
    FORTH_PRIMITIVE_LOWER,
    FORTH_PRIMITIVE_EQUAL,
    FORTH_PRIMITIVE_AND,
    FORTH_PRIMITIVE_OR,
    FORTH_PRIMITIVE_XOR,
    FORTH_PRIMITIVE_DISP,
    NUM_PRIMITIVES
  };

// TODO: ASSERT_COMPILE_TIME(NUM_PRIMITIVES < sizeof (Cell16))

#endif /* FORTH_PRIMITIVES_HPP_ */
