/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_win_main (void)
{
  GtkWidget *win_main;
  GtkWidget *hpaned1;
  GtkWidget *vbox_drawing;
  GtkWidget *en_prompt;
  GtkWidget *hbox1;
  GtkWidget *toolbar4;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *tg_mode_som;
  GtkWidget *tg_mode_arc;
  GtkWidget *tg_mode_zone;
  GtkWidget *tg_mode_ajout;
  GtkWidget *tg_mode_supp;
  GtkWidget *tg_mode_select;
  GtkWidget *tg_mode_deplace;
  GtkWidget *tg_mode_vue;
  GtkWidget *bt_execute_carte;
  GtkWidget *tg_show_champ;
  GtkWidget *tg_show_forth;
  GtkWidget *bt_show_color;
  GtkWidget *bt_connexion_mysql;
  GtkWidget *vpaned1;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *separator5;
  GtkWidget *cartes_item1;
  GtkWidget *image82;
  GtkWidget *separator4;
  GtkWidget *conexion_serveur;
  GtkWidget *image83;
  GtkWidget *exporter_carte;
  GtkWidget *image84;
  GtkWidget *separator1;
  GtkWidget *forth_item;
  GtkWidget *image85;
  GtkWidget *separator6;
  GtkWidget *nouveau1;
  GtkWidget *ouvrir1;
  GtkWidget *enregistrer1;
  GtkWidget *enregistrer_sous1;
  GtkWidget *exporter_code_forth;
  GtkWidget *image86;
  GtkWidget *separatormenuitem1;
  GtkWidget *quitter1;
  GtkWidget *menuitem2;
  GtkWidget *menuitem2_menu;
  GtkWidget *couper1;
  GtkWidget *copier1;
  GtkWidget *coller1;
  GtkWidget *supprimer1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *___propos1;
  GtkWidget *image87;
  GtkWidget *ntbk_main;
  GtkWidget *scrolledwindow1;
  GtkWidget *tv_nouv;
  GtkWidget *label1;
  GtkWidget *vbox2;
  GtkWidget *handlebox2;
  GtkWidget *toolbar3;
  GtkWidget *bt_execute;
  GtkWidget *bt_debug;
  GtkWidget *bt_RAZ;
  GtkWidget *bt_abort;
  GtkWidget *ntbk_sec;
  GtkWidget *scrolledwindow2;
  GtkWidget *tv_res;
  GtkWidget *label2;
  GtkWidget *scrolledwindow3;
  GtkWidget *tv_svgd_code;
  GtkWidget *label3;
  GtkWidget *scrolledwindow4;
  GtkWidget *tv_debug;
  GtkWidget *label4;
  GtkWidget *scrolledwindow5;
  GtkWidget *tree_dico;
  GtkWidget *label5;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  win_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (win_main, 800, 600);
  gtk_window_set_title (GTK_WINDOW (win_main), _("SimTaDyn"));
  gtk_window_set_position (GTK_WINDOW (win_main), GTK_WIN_POS_CENTER);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_container_add (GTK_CONTAINER (win_main), hpaned1);
  gtk_paned_set_position (GTK_PANED (hpaned1), 300);

  vbox_drawing = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_drawing);
  gtk_paned_pack1 (GTK_PANED (hpaned1), vbox_drawing, FALSE, TRUE);

  en_prompt = gtk_entry_new ();
  gtk_widget_show (en_prompt);
  gtk_box_pack_start (GTK_BOX (vbox_drawing), en_prompt, FALSE, FALSE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), hbox1, TRUE, TRUE);

  toolbar4 = gtk_toolbar_new ();
  gtk_widget_show (toolbar4);
  gtk_box_pack_start (GTK_BOX (hbox1), toolbar4, FALSE, TRUE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar4), GTK_TOOLBAR_ICONS);
  gtk_toolbar_set_orientation (GTK_TOOLBAR (toolbar4), GTK_ORIENTATION_VERTICAL);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-no", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  tg_mode_som = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("togglebutton1"),
                                _("Passer en mode SOMMET"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (tg_mode_som);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-yes", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  tg_mode_arc = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("togglebutton2"),
                                _("Passer en mode ARC"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (tg_mode_arc);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-home", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  tg_mode_zone = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("togglebutton3"),
                                _("Passer en mode ZONE"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (tg_mode_zone);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar4));

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-add", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  tg_mode_ajout = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("togglebutton4"),
                                _("Ajouter une cellule"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (tg_mode_ajout);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-remove", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  tg_mode_supp = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("togglebutton5"),
                                _("Supprimer une cellule"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (tg_mode_supp);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-jump-to", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  tg_mode_select = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("togglebutton6"),
                                _("S\303\251lectionner une cellule"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (tg_mode_select);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-undo", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  tg_mode_deplace = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("togglebutton7"),
                                _("D\303\251placer une cellule"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (tg_mode_deplace);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-convert", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  tg_mode_vue = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("togglebutton8"),
                                _("Commuter l'affichage 2D / 3D"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (tg_mode_vue);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-execute", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  bt_execute_carte = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button2"),
                                _("Ex\303\251cuter n fois tous les mots FORTH de la carte, o\303\271 n est un nombre entier stock\303\251 sur le sommet de la pile de donn\303\251es."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (bt_execute_carte);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar4));

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-index", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  tg_show_champ = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("togglebutton9"),
                                _("Afficher ou cacher le visualisateur de noms des champs des cellules"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (tg_show_champ);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (tg_show_champ), TRUE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-bold", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  tg_show_forth = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("togglebutton10"),
                                _("Afficher ou cacher l'\303\251diteur FORTH"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (tg_show_forth);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-select-color", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  bt_show_color = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button1"),
                                _("Afficher ou cacher la fen\303\252tre de s\303\251lection des couleurs"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (bt_show_color);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-quit", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4)));
  bt_connexion_mysql = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar4),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("button1"),
                                _("Fen\303\252tre de connexion au serveur MySQL"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar4)->children)->data))->label), TRUE);
  gtk_widget_show (bt_connexion_mysql);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_show (vpaned1);
  gtk_box_pack_start (GTK_BOX (hbox1), vpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (vpaned1), 350);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_paned_pack1 (GTK_PANED (vpaned1), vbox1, FALSE, TRUE);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, TRUE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_Carte/Fichier"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  separator5 = gtk_menu_item_new ();
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  cartes_item1 = gtk_image_menu_item_new_with_mnemonic (_("CARTES GEOGRAPHIQUES"));
  gtk_widget_show (cartes_item1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), cartes_item1);

  image82 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image82);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (cartes_item1), image82);

  separator4 = gtk_menu_item_new ();
  gtk_widget_show (separator4);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator4);
  gtk_widget_set_sensitive (separator4, FALSE);

  conexion_serveur = gtk_image_menu_item_new_with_mnemonic (_("Connexion serveur MySQL"));
  gtk_widget_show (conexion_serveur);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), conexion_serveur);
  gtk_widget_add_accelerator (conexion_serveur, "activate", accel_group,
                              GDK_N, GDK_CONTROL_MASK | GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  image83 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image83);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (conexion_serveur), image83);

  exporter_carte = gtk_image_menu_item_new_with_mnemonic (_("Exporter Carte"));
  gtk_widget_show (exporter_carte);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), exporter_carte);
  gtk_widget_add_accelerator (exporter_carte, "activate", accel_group,
                              GDK_E, GDK_SHIFT_MASK,
                              GTK_ACCEL_VISIBLE);

  image84 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image84);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (exporter_carte), image84);

  separator1 = gtk_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  forth_item = gtk_image_menu_item_new_with_mnemonic (_("FICHIERS FORTH"));
  gtk_widget_show (forth_item);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), forth_item);

  image85 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image85);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (forth_item), image85);

  separator6 = gtk_menu_item_new ();
  gtk_widget_show (separator6);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separator6);
  gtk_widget_set_sensitive (separator6, FALSE);

  nouveau1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (nouveau1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), nouveau1);

  ouvrir1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (ouvrir1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), ouvrir1);

  enregistrer1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (enregistrer1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), enregistrer1);

  enregistrer_sous1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (enregistrer_sous1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), enregistrer_sous1);

  exporter_code_forth = gtk_image_menu_item_new_with_mnemonic (_("Exporter"));
  gtk_widget_show (exporter_code_forth);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), exporter_code_forth);

  image86 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image86);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (exporter_code_forth), image86);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quitter1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quitter1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quitter1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_\303\211dition"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menuitem2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  couper1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (couper1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), couper1);

  copier1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copier1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), copier1);

  coller1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (coller1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), coller1);

  supprimer1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (supprimer1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), supprimer1);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Aide"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  ___propos1 = gtk_image_menu_item_new_with_mnemonic (_("\303\200 _propos"));
  gtk_widget_show (___propos1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), ___propos1);

  image87 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image87);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (___propos1), image87);

  ntbk_main = gtk_notebook_new ();
  gtk_widget_show (ntbk_main);
  gtk_box_pack_start (GTK_BOX (vbox1), ntbk_main, TRUE, TRUE, 0);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (ntbk_main), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (ntbk_main), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  tv_nouv = gtk_text_view_new ();
  gtk_widget_show (tv_nouv);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), tv_nouv);

  label1 = gtk_label_new (_("Nouveau"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (ntbk_main), gtk_notebook_get_nth_page (GTK_NOTEBOOK (ntbk_main), 0), label1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_paned_pack2 (GTK_PANED (vpaned1), vbox2, TRUE, TRUE);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox2), handlebox2, FALSE, FALSE, 0);

  toolbar3 = gtk_toolbar_new ();
  gtk_widget_show (toolbar3);
  gtk_container_add (GTK_CONTAINER (handlebox2), toolbar3);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar3), GTK_TOOLBAR_BOTH);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-execute", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar3)));
  bt_execute = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Ex\303\251cuter"),
                                _("Ex\303\251cuter ou compiler un programme FORTH"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar3)->children)->data))->label), TRUE);
  gtk_widget_show (bt_execute);
  gtk_widget_add_accelerator (bt_execute, "clicked", accel_group,
                              GDK_Return, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-convert", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar3)));
  bt_debug = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("D\303\251bugger"),
                                _("Lancer ou arr\303\252ter le d\303\251bugger"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar3)->children)->data))->label), TRUE);
  gtk_widget_show (bt_debug);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-delete", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar3)));
  bt_RAZ = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("RAZ dico"),
                                _("Remise \303\240 z\303\251ro du dictionnaire FORTH"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar3)->children)->data))->label), TRUE);
  gtk_widget_show (bt_RAZ);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-dialog-warning", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar3)));
  bt_abort = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar3),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("R\303\251initialiser"),
                                _("Remise \303\240 z\303\251ro de la pile de donn\303\251es et de retour puis rem\303\252t l'interpr\303\251teur en mode ex\303\251cution."), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar3)->children)->data))->label), TRUE);
  gtk_widget_show (bt_abort);

  ntbk_sec = gtk_notebook_new ();
  gtk_widget_show (ntbk_sec);
  gtk_box_pack_start (GTK_BOX (vbox2), ntbk_sec, TRUE, TRUE, 0);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (ntbk_sec), TRUE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (ntbk_sec), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  tv_res = gtk_text_view_new ();
  gtk_widget_show (tv_res);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), tv_res);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (tv_res), GTK_WRAP_WORD);

  label2 = gtk_label_new (_("R\303\251sultat"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (ntbk_sec), gtk_notebook_get_nth_page (GTK_NOTEBOOK (ntbk_sec), 0), label2);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (ntbk_sec), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  tv_svgd_code = gtk_text_view_new ();
  gtk_widget_show (tv_svgd_code);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), tv_svgd_code);

  label3 = gtk_label_new (_("Code"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (ntbk_sec), gtk_notebook_get_nth_page (GTK_NOTEBOOK (ntbk_sec), 1), label3);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (ntbk_sec), scrolledwindow4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  tv_debug = gtk_text_view_new ();
  gtk_widget_show (tv_debug);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), tv_debug);

  label4 = gtk_label_new (_("D\303\251bug"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (ntbk_sec), gtk_notebook_get_nth_page (GTK_NOTEBOOK (ntbk_sec), 2), label4);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_container_add (GTK_CONTAINER (ntbk_sec), scrolledwindow5);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  tree_dico = gtk_tree_view_new ();
  gtk_widget_show (tree_dico);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), tree_dico);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (tree_dico), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (tree_dico), TRUE);

  label5 = gtk_label_new (_("Dico"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (ntbk_sec), gtk_notebook_get_nth_page (GTK_NOTEBOOK (ntbk_sec), 3), label5);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox2), statusbar, FALSE, FALSE, 0);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (statusbar), FALSE);

  g_signal_connect ((gpointer) win_main, "destroy_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) win_main, "delete_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) en_prompt, "activate",
                    G_CALLBACK (on_en_prompt_activate),
                    NULL);
  g_signal_connect ((gpointer) tg_mode_som, "toggled",
                    G_CALLBACK (on_tg_mode_som_toggled),
                    NULL);
  g_signal_connect ((gpointer) tg_mode_arc, "toggled",
                    G_CALLBACK (on_tg_mode_arc_toggled),
                    NULL);
  g_signal_connect ((gpointer) tg_mode_zone, "toggled",
                    G_CALLBACK (on_tg_mode_zone_toggled),
                    NULL);
  g_signal_connect ((gpointer) tg_mode_ajout, "clicked",
                    G_CALLBACK (on_tg_mode_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) tg_mode_supp, "clicked",
                    G_CALLBACK (on_tg_mode_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) tg_mode_select, "clicked",
                    G_CALLBACK (on_tg_mode_select_clicked),
                    NULL);
  g_signal_connect ((gpointer) tg_mode_deplace, "clicked",
                    G_CALLBACK (on_tg_mode_deplace_clicked),
                    NULL);
  g_signal_connect ((gpointer) tg_mode_vue, "clicked",
                    G_CALLBACK (on_tg_mode_vue_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_execute_carte, "clicked",
                    G_CALLBACK (on_bt_execute_carte_clicked),
                    NULL);
  g_signal_connect ((gpointer) tg_show_champ, "clicked",
                    G_CALLBACK (on_tg_show_champ_clicked),
                    NULL);
  g_signal_connect ((gpointer) tg_show_forth, "clicked",
                    G_CALLBACK (on_tg_show_forth_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_show_color, "clicked",
                    G_CALLBACK (on_bt_show_color_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_connexion_mysql, "clicked",
                    G_CALLBACK (on_bt_connexion_mysql_clicked),
                    NULL);
  g_signal_connect ((gpointer) conexion_serveur, "activate",
                    G_CALLBACK (conexion_serveur_activate),
                    NULL);
  g_signal_connect ((gpointer) exporter_carte, "activate",
                    G_CALLBACK (on_exporter_carte_activate),
                    NULL);
  g_signal_connect ((gpointer) nouveau1, "activate",
                    G_CALLBACK (on_nouveau1_activate),
                    NULL);
  g_signal_connect ((gpointer) ouvrir1, "activate",
                    G_CALLBACK (on_ouvrir1_activate),
                    NULL);
  g_signal_connect ((gpointer) enregistrer1, "activate",
                    G_CALLBACK (on_enregistrer1_activate),
                    NULL);
  g_signal_connect ((gpointer) enregistrer_sous1, "activate",
                    G_CALLBACK (on_enregistrer_sous1_activate),
                    NULL);
  g_signal_connect ((gpointer) exporter_code_forth, "activate",
                    G_CALLBACK (on_exporter_code_forth_activate),
                    NULL);
  g_signal_connect ((gpointer) quitter1, "activate",
                    G_CALLBACK (on_quitter1_activate),
                    NULL);
  g_signal_connect ((gpointer) couper1, "activate",
                    G_CALLBACK (on_couper1_activate),
                    NULL);
  g_signal_connect ((gpointer) copier1, "activate",
                    G_CALLBACK (on_copier1_activate),
                    NULL);
  g_signal_connect ((gpointer) coller1, "activate",
                    G_CALLBACK (on_coller1_activate),
                    NULL);
  g_signal_connect ((gpointer) supprimer1, "activate",
                    G_CALLBACK (on_supprimer1_activate),
                    NULL);
  g_signal_connect ((gpointer) ___propos1, "activate",
                    G_CALLBACK (on_a_propos1_activate),
                    NULL);
  g_signal_connect ((gpointer) bt_execute, "clicked",
                    G_CALLBACK (on_bt_execute_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_debug, "clicked",
                    G_CALLBACK (on_bt_debug_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_RAZ, "clicked",
                    G_CALLBACK (on_bt_RAZ_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_abort, "clicked",
                    G_CALLBACK (on_bt_abort_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_main, win_main, "win_main");
  GLADE_HOOKUP_OBJECT (win_main, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (win_main, vbox_drawing, "vbox_drawing");
  GLADE_HOOKUP_OBJECT (win_main, en_prompt, "en_prompt");
  GLADE_HOOKUP_OBJECT (win_main, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (win_main, toolbar4, "toolbar4");
  GLADE_HOOKUP_OBJECT (win_main, tg_mode_som, "tg_mode_som");
  GLADE_HOOKUP_OBJECT (win_main, tg_mode_arc, "tg_mode_arc");
  GLADE_HOOKUP_OBJECT (win_main, tg_mode_zone, "tg_mode_zone");
  GLADE_HOOKUP_OBJECT (win_main, tg_mode_ajout, "tg_mode_ajout");
  GLADE_HOOKUP_OBJECT (win_main, tg_mode_supp, "tg_mode_supp");
  GLADE_HOOKUP_OBJECT (win_main, tg_mode_select, "tg_mode_select");
  GLADE_HOOKUP_OBJECT (win_main, tg_mode_deplace, "tg_mode_deplace");
  GLADE_HOOKUP_OBJECT (win_main, tg_mode_vue, "tg_mode_vue");
  GLADE_HOOKUP_OBJECT (win_main, bt_execute_carte, "bt_execute_carte");
  GLADE_HOOKUP_OBJECT (win_main, tg_show_champ, "tg_show_champ");
  GLADE_HOOKUP_OBJECT (win_main, tg_show_forth, "tg_show_forth");
  GLADE_HOOKUP_OBJECT (win_main, bt_show_color, "bt_show_color");
  GLADE_HOOKUP_OBJECT (win_main, bt_connexion_mysql, "bt_connexion_mysql");
  GLADE_HOOKUP_OBJECT (win_main, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (win_main, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (win_main, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (win_main, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (win_main, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (win_main, separator5, "separator5");
  GLADE_HOOKUP_OBJECT (win_main, cartes_item1, "cartes_item1");
  GLADE_HOOKUP_OBJECT (win_main, image82, "image82");
  GLADE_HOOKUP_OBJECT (win_main, separator4, "separator4");
  GLADE_HOOKUP_OBJECT (win_main, conexion_serveur, "conexion_serveur");
  GLADE_HOOKUP_OBJECT (win_main, image83, "image83");
  GLADE_HOOKUP_OBJECT (win_main, exporter_carte, "exporter_carte");
  GLADE_HOOKUP_OBJECT (win_main, image84, "image84");
  GLADE_HOOKUP_OBJECT (win_main, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (win_main, forth_item, "forth_item");
  GLADE_HOOKUP_OBJECT (win_main, image85, "image85");
  GLADE_HOOKUP_OBJECT (win_main, separator6, "separator6");
  GLADE_HOOKUP_OBJECT (win_main, nouveau1, "nouveau1");
  GLADE_HOOKUP_OBJECT (win_main, ouvrir1, "ouvrir1");
  GLADE_HOOKUP_OBJECT (win_main, enregistrer1, "enregistrer1");
  GLADE_HOOKUP_OBJECT (win_main, enregistrer_sous1, "enregistrer_sous1");
  GLADE_HOOKUP_OBJECT (win_main, exporter_code_forth, "exporter_code_forth");
  GLADE_HOOKUP_OBJECT (win_main, image86, "image86");
  GLADE_HOOKUP_OBJECT (win_main, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (win_main, quitter1, "quitter1");
  GLADE_HOOKUP_OBJECT (win_main, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (win_main, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (win_main, couper1, "couper1");
  GLADE_HOOKUP_OBJECT (win_main, copier1, "copier1");
  GLADE_HOOKUP_OBJECT (win_main, coller1, "coller1");
  GLADE_HOOKUP_OBJECT (win_main, supprimer1, "supprimer1");
  GLADE_HOOKUP_OBJECT (win_main, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (win_main, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (win_main, ___propos1, "___propos1");
  GLADE_HOOKUP_OBJECT (win_main, image87, "image87");
  GLADE_HOOKUP_OBJECT (win_main, ntbk_main, "ntbk_main");
  GLADE_HOOKUP_OBJECT (win_main, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (win_main, tv_nouv, "tv_nouv");
  GLADE_HOOKUP_OBJECT (win_main, label1, "label1");
  GLADE_HOOKUP_OBJECT (win_main, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (win_main, handlebox2, "handlebox2");
  GLADE_HOOKUP_OBJECT (win_main, toolbar3, "toolbar3");
  GLADE_HOOKUP_OBJECT (win_main, bt_execute, "bt_execute");
  GLADE_HOOKUP_OBJECT (win_main, bt_debug, "bt_debug");
  GLADE_HOOKUP_OBJECT (win_main, bt_RAZ, "bt_RAZ");
  GLADE_HOOKUP_OBJECT (win_main, bt_abort, "bt_abort");
  GLADE_HOOKUP_OBJECT (win_main, ntbk_sec, "ntbk_sec");
  GLADE_HOOKUP_OBJECT (win_main, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (win_main, tv_res, "tv_res");
  GLADE_HOOKUP_OBJECT (win_main, label2, "label2");
  GLADE_HOOKUP_OBJECT (win_main, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (win_main, tv_svgd_code, "tv_svgd_code");
  GLADE_HOOKUP_OBJECT (win_main, label3, "label3");
  GLADE_HOOKUP_OBJECT (win_main, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (win_main, tv_debug, "tv_debug");
  GLADE_HOOKUP_OBJECT (win_main, label4, "label4");
  GLADE_HOOKUP_OBJECT (win_main, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (win_main, tree_dico, "tree_dico");
  GLADE_HOOKUP_OBJECT (win_main, label5, "label5");
  GLADE_HOOKUP_OBJECT (win_main, statusbar, "statusbar");

  gtk_window_add_accel_group (GTK_WINDOW (win_main), accel_group);

  return win_main;
}

GtkWidget*
create_win_about (void)
{
  GtkWidget *win_about;
  GtkWidget *vbox3;
  GtkWidget *hbox3;
  GtkWidget *image6;
  GtkWidget *label11;
  GtkWidget *hseparator1;
  GtkWidget *hbuttonbox1;
  GtkWidget *bt_win_about_fermer;

  win_about = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (win_about, 230, 132);
  gtk_window_set_title (GTK_WINDOW (win_about), _("Apropos de SimTaDyn"));
  gtk_window_set_position (GTK_WINDOW (win_about), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (win_about), FALSE);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (win_about), vbox3);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, FALSE, FALSE, 0);

  image6 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox3), image6, TRUE, FALSE, 0);

  label11 = gtk_label_new (_("SIMTADYN\n\nInfo Sp\303\251 2003 -- 2004 EPITA\n\nQuentin QUADRAT\nMinh Long NGUYEN\nBenoit MARCOT"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_CENTER);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox3), hseparator1, FALSE, TRUE, 5);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox1, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  bt_win_about_fermer = gtk_button_new_from_stock ("gtk-yes");
  gtk_widget_show (bt_win_about_fermer);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), bt_win_about_fermer);
  GTK_WIDGET_SET_FLAGS (bt_win_about_fermer, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) win_about, "delete_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);
  g_signal_connect ((gpointer) win_about, "destroy_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);
  g_signal_connect ((gpointer) bt_win_about_fermer, "clicked",
                    G_CALLBACK (on_bt_win_about_fermer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_about, win_about, "win_about");
  GLADE_HOOKUP_OBJECT (win_about, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (win_about, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (win_about, image6, "image6");
  GLADE_HOOKUP_OBJECT (win_about, label11, "label11");
  GLADE_HOOKUP_OBJECT (win_about, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (win_about, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (win_about, bt_win_about_fermer, "bt_win_about_fermer");

  return win_about;
}

GtkWidget*
create_win_quitte (void)
{
  GtkWidget *win_quitte;
  GtkWidget *vbox4;
  GtkWidget *hbuttonbox2;
  GtkWidget *bt_win_quit_annule;
  GtkWidget *bt_win_quitte_quitter;
  GtkWidget *hbox2;
  GtkWidget *image5;
  GtkWidget *label9;
  GtkWidget *hseparator2;

  win_quitte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (win_quitte), _("Attention !!!"));
  gtk_window_set_position (GTK_WINDOW (win_quitte), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (win_quitte), FALSE);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (win_quitte), vbox4);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_end (GTK_BOX (vbox4), hbuttonbox2, TRUE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox2), 7);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_EDGE);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox2), 7);

  bt_win_quit_annule = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (bt_win_quit_annule);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), bt_win_quit_annule);
  GTK_WIDGET_SET_FLAGS (bt_win_quit_annule, GTK_CAN_DEFAULT);

  bt_win_quitte_quitter = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (bt_win_quitte_quitter);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), bt_win_quitte_quitter);
  GTK_WIDGET_SET_FLAGS (bt_win_quitte_quitter, GTK_CAN_DEFAULT);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox2, FALSE, FALSE, 17);

  image5 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox2), image5, TRUE, TRUE, 6);

  label9 = gtk_label_new (_("Voulez vous\nvraiment quitter \nSimTaDyn ?!"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_CENTER);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox4), hseparator2, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) win_quitte, "destroy_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);
  g_signal_connect ((gpointer) win_quitte, "delete_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);
  g_signal_connect ((gpointer) bt_win_quit_annule, "clicked",
                    G_CALLBACK (on_bt_win_quit_annule_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_win_quitte_quitter, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_quitte, win_quitte, "win_quitte");
  GLADE_HOOKUP_OBJECT (win_quitte, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (win_quitte, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (win_quitte, bt_win_quit_annule, "bt_win_quit_annule");
  GLADE_HOOKUP_OBJECT (win_quitte, bt_win_quitte_quitter, "bt_win_quitte_quitter");
  GLADE_HOOKUP_OBJECT (win_quitte, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (win_quitte, image5, "image5");
  GLADE_HOOKUP_OBJECT (win_quitte, label9, "label9");
  GLADE_HOOKUP_OBJECT (win_quitte, hseparator2, "hseparator2");

  return win_quitte;
}

GtkWidget*
create_win_open (void)
{
  GtkWidget *win_open;
  GtkWidget *bt_win_open_ok_button;
  GtkWidget *bt_win_open_cancel_button;

  win_open = gtk_file_selection_new (_("Ouvrir un fichier"));
  gtk_container_set_border_width (GTK_CONTAINER (win_open), 10);

  bt_win_open_ok_button = GTK_FILE_SELECTION (win_open)->ok_button;
  gtk_widget_show (bt_win_open_ok_button);
  GTK_WIDGET_SET_FLAGS (bt_win_open_ok_button, GTK_CAN_DEFAULT);

  bt_win_open_cancel_button = GTK_FILE_SELECTION (win_open)->cancel_button;
  gtk_widget_show (bt_win_open_cancel_button);
  GTK_WIDGET_SET_FLAGS (bt_win_open_cancel_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) bt_win_open_ok_button, "clicked",
                    G_CALLBACK (on_bt_win_open_ok_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_win_open_cancel_button, "clicked",
                    G_CALLBACK (on_bt_win_open_cancel_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_open, win_open, "win_open");
  GLADE_HOOKUP_OBJECT_NO_REF (win_open, bt_win_open_ok_button, "bt_win_open_ok_button");
  GLADE_HOOKUP_OBJECT_NO_REF (win_open, bt_win_open_cancel_button, "bt_win_open_cancel_button");

  return win_open;
}

GtkWidget*
create_win_save (void)
{
  GtkWidget *win_save;
  GtkWidget *bt_win_save_ok_button;
  GtkWidget *bt_win_save_cancel_button;

  win_save = gtk_file_selection_new (_("Sauver un fichier"));
  gtk_container_set_border_width (GTK_CONTAINER (win_save), 10);

  bt_win_save_ok_button = GTK_FILE_SELECTION (win_save)->ok_button;
  gtk_widget_show (bt_win_save_ok_button);
  GTK_WIDGET_SET_FLAGS (bt_win_save_ok_button, GTK_CAN_DEFAULT);

  bt_win_save_cancel_button = GTK_FILE_SELECTION (win_save)->cancel_button;
  gtk_widget_show (bt_win_save_cancel_button);
  GTK_WIDGET_SET_FLAGS (bt_win_save_cancel_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) bt_win_save_ok_button, "clicked",
                    G_CALLBACK (on_bt_win_save_ok_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_win_save_cancel_button, "clicked",
                    G_CALLBACK (on_bt_win_save_cancel_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_save, win_save, "win_save");
  GLADE_HOOKUP_OBJECT_NO_REF (win_save, bt_win_save_ok_button, "bt_win_save_ok_button");
  GLADE_HOOKUP_OBJECT_NO_REF (win_save, bt_win_save_cancel_button, "bt_win_save_cancel_button");

  return win_save;
}

GtkWidget*
create_win_RAZ (void)
{
  GtkWidget *win_RAZ;
  GtkWidget *vbox5;
  GtkWidget *hbox4;
  GtkWidget *image8;
  GtkWidget *label10;
  GtkWidget *hseparator3;
  GtkWidget *hbuttonbox3;
  GtkWidget *bt_RAZ_non;
  GtkWidget *bt_RAZ_oui;

  win_RAZ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (win_RAZ, 230, 220);
  gtk_window_set_title (GTK_WINDOW (win_RAZ), _("ATTENTION !!!!"));
  gtk_window_set_position (GTK_WINDOW (win_RAZ), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (win_RAZ), FALSE);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (win_RAZ), vbox5);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox4, TRUE, TRUE, 3);

  image8 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox4), image8, FALSE, TRUE, 11);

  label10 = gtk_label_new (_("Attention ! \n\nVouz allez remettre \303\240\nz\303\251ro le dictionnaire.\nToutes vos donn\303\251es \nseront perdues.\n\nVoulez-vous vraiment\ncontinuer ?"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_CENTER);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox5), hseparator3, FALSE, TRUE, 2);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox5), hbuttonbox3, FALSE, TRUE, 2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_SPREAD);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox3), 6);

  bt_RAZ_non = gtk_button_new_from_stock ("gtk-no");
  gtk_widget_show (bt_RAZ_non);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), bt_RAZ_non);
  GTK_WIDGET_SET_FLAGS (bt_RAZ_non, GTK_CAN_DEFAULT);

  bt_RAZ_oui = gtk_button_new_from_stock ("gtk-yes");
  gtk_widget_show (bt_RAZ_oui);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), bt_RAZ_oui);
  GTK_WIDGET_SET_FLAGS (bt_RAZ_oui, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) bt_RAZ_non, "clicked",
                    G_CALLBACK (on_bt_RAZ_non_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_RAZ_oui, "clicked",
                    G_CALLBACK (on_bt_RAZ_oui_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_RAZ, win_RAZ, "win_RAZ");
  GLADE_HOOKUP_OBJECT (win_RAZ, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (win_RAZ, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (win_RAZ, image8, "image8");
  GLADE_HOOKUP_OBJECT (win_RAZ, label10, "label10");
  GLADE_HOOKUP_OBJECT (win_RAZ, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (win_RAZ, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (win_RAZ, bt_RAZ_non, "bt_RAZ_non");
  GLADE_HOOKUP_OBJECT (win_RAZ, bt_RAZ_oui, "bt_RAZ_oui");

  return win_RAZ;
}

GtkWidget*
create_win_gconex (void)
{
  GtkWidget *win_gconex;
  GtkWidget *vbox11;
  GtkWidget *hbox15;
  GtkWidget *image40;
  GtkWidget *frame5;
  GtkWidget *table3;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *en_host;
  GtkWidget *en_user;
  GtkWidget *en_pswd;
  GtkWidget *label28;
  GtkWidget *vbox12;
  GtkWidget *frame6;
  GtkWidget *table4;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *bt_nouvelle_carte;
  GtkWidget *bt_supp_carte;
  GtkWidget *bt_charger_carte;
  GtkWidget *label30;
  GtkWidget *entry_database;
  GtkWidget *combo_supp;
  GtkWidget *combo_entry_supp;
  GtkWidget *combo_charger;
  GtkWidget *combo_entry_charger;
  GtkWidget *combo1;
  GtkWidget *combo_entry1;
  GtkWidget *bt_exporter;
  GtkWidget *label36;
  GtkWidget *bt_importer;
  GtkWidget *label37;
  GtkWidget *combo2;
  GtkWidget *combo_entry2;
  GtkWidget *label29;
  GtkWidget *hbuttonbox4;
  GtkWidget *bt_cancel_win_gconnex;

  win_gconex = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (win_gconex, 400, 384);
  gtk_window_set_title (GTK_WINDOW (win_gconex), _("Connexion serveur"));
  gtk_window_set_resizable (GTK_WINDOW (win_gconex), FALSE);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (win_gconex), vbox11);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox15, TRUE, TRUE, 0);

  image40 = create_pixmap (win_gconex, "network_local.png");
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox15), image40, FALSE, TRUE, 0);
  gtk_widget_set_size_request (image40, -1, 30);
  gtk_misc_set_alignment (GTK_MISC (image40), 0, 0);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (hbox15), frame5, TRUE, TRUE, 0);
  gtk_widget_set_size_request (frame5, -1, 30);

  table3 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (frame5), table3);

  label25 = gtk_label_new (_("Host :"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table3), label25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new (_("User :"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table3), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new (_("Password :"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table3), label27, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  en_host = gtk_entry_new ();
  gtk_widget_show (en_host);
  gtk_table_attach (GTK_TABLE (table3), en_host, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (en_host), _("localhost"));

  en_user = gtk_entry_new ();
  gtk_widget_show (en_user);
  gtk_table_attach (GTK_TABLE (table3), en_user, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (en_user), _("quadrat"));

  en_pswd = gtk_entry_new ();
  gtk_widget_show (en_pswd);
  gtk_table_attach (GTK_TABLE (table3), en_pswd, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_visibility (GTK_ENTRY (en_pswd), FALSE);
  gtk_entry_set_text (GTK_ENTRY (en_pswd), _("1que1ti1"));

  label28 = gtk_label_new (_("Connexion \303\240 un serveur de carte MySQL"));
  gtk_widget_show (label28);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label28);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (vbox11), vbox12, TRUE, TRUE, 0);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox12), frame6, TRUE, TRUE, 0);

  table4 = gtk_table_new (5, 3, FALSE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (frame6), table4);
  gtk_widget_set_size_request (table4, -1, 34);

  label31 = gtk_label_new (_("Supprimer :"));
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table4), label31, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  label32 = gtk_label_new (_("Database  :"));
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table4), label32, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  bt_nouvelle_carte = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (bt_nouvelle_carte);
  gtk_table_attach (GTK_TABLE (table4), bt_nouvelle_carte, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bt_supp_carte = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (bt_supp_carte);
  gtk_table_attach (GTK_TABLE (table4), bt_supp_carte, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  bt_charger_carte = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (bt_charger_carte);
  gtk_table_attach (GTK_TABLE (table4), bt_charger_carte, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label30 = gtk_label_new (_("Nouvelle   :"));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table4), label30, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  entry_database = gtk_entry_new ();
  gtk_widget_show (entry_database);
  gtk_table_attach (GTK_TABLE (table4), entry_database, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_supp = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_supp)->popwin),
                     "GladeParentKey", combo_supp);
  gtk_widget_show (combo_supp);
  gtk_table_attach (GTK_TABLE (table4), combo_supp, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry_supp = GTK_COMBO (combo_supp)->entry;
  gtk_widget_show (combo_entry_supp);

  combo_charger = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_charger)->popwin),
                     "GladeParentKey", combo_charger);
  gtk_widget_show (combo_charger);
  gtk_table_attach (GTK_TABLE (table4), combo_charger, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry_charger = GTK_COMBO (combo_charger)->entry;
  gtk_widget_show (combo_entry_charger);
  gtk_entry_set_text (GTK_ENTRY (combo_entry_charger), _("quadrat"));

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_table_attach (GTK_TABLE (table4), combo1, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry1 = GTK_COMBO (combo1)->entry;
  gtk_widget_show (combo_entry1);

  bt_exporter = gtk_button_new_with_mnemonic (_("button1"));
  gtk_widget_show (bt_exporter);
  gtk_table_attach (GTK_TABLE (table4), bt_exporter, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label36 = gtk_label_new (_("Exporter"));
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table4), label36, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  bt_importer = gtk_button_new_with_mnemonic (_("button2"));
  gtk_widget_show (bt_importer);
  gtk_table_attach (GTK_TABLE (table4), bt_importer, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label37 = gtk_label_new (_("Importer"));
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table4), label37, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  combo2 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo2)->popwin),
                     "GladeParentKey", combo2);
  gtk_widget_show (combo2);
  gtk_table_attach (GTK_TABLE (table4), combo2, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry2 = GTK_COMBO (combo2)->entry;
  gtk_widget_show (combo_entry2);

  label29 = gtk_label_new (_("Gestion de cartes"));
  gtk_widget_show (label29);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label29);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox12), hbuttonbox4, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox4), 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_START);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox4), 5);

  bt_cancel_win_gconnex = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (bt_cancel_win_gconnex);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), bt_cancel_win_gconnex);
  GTK_WIDGET_SET_FLAGS (bt_cancel_win_gconnex, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) win_gconex, "destroy_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);
  g_signal_connect ((gpointer) win_gconex, "delete_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);
  g_signal_connect ((gpointer) bt_nouvelle_carte, "clicked",
                    G_CALLBACK (on_bt_nouvelle_carte_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_supp_carte, "clicked",
                    G_CALLBACK (on_bt_supp_carte_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_charger_carte, "clicked",
                    G_CALLBACK (on_bt_charger_carte_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_exporter, "clicked",
                    G_CALLBACK (on_bt_exporter_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_importer, "clicked",
                    G_CALLBACK (on_bt_importer_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_cancel_win_gconnex, "clicked",
                    G_CALLBACK (on_bt_cancel_win_gconnex_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_gconex, win_gconex, "win_gconex");
  GLADE_HOOKUP_OBJECT (win_gconex, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (win_gconex, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (win_gconex, image40, "image40");
  GLADE_HOOKUP_OBJECT (win_gconex, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (win_gconex, table3, "table3");
  GLADE_HOOKUP_OBJECT (win_gconex, label25, "label25");
  GLADE_HOOKUP_OBJECT (win_gconex, label26, "label26");
  GLADE_HOOKUP_OBJECT (win_gconex, label27, "label27");
  GLADE_HOOKUP_OBJECT (win_gconex, en_host, "en_host");
  GLADE_HOOKUP_OBJECT (win_gconex, en_user, "en_user");
  GLADE_HOOKUP_OBJECT (win_gconex, en_pswd, "en_pswd");
  GLADE_HOOKUP_OBJECT (win_gconex, label28, "label28");
  GLADE_HOOKUP_OBJECT (win_gconex, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (win_gconex, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (win_gconex, table4, "table4");
  GLADE_HOOKUP_OBJECT (win_gconex, label31, "label31");
  GLADE_HOOKUP_OBJECT (win_gconex, label32, "label32");
  GLADE_HOOKUP_OBJECT (win_gconex, bt_nouvelle_carte, "bt_nouvelle_carte");
  GLADE_HOOKUP_OBJECT (win_gconex, bt_supp_carte, "bt_supp_carte");
  GLADE_HOOKUP_OBJECT (win_gconex, bt_charger_carte, "bt_charger_carte");
  GLADE_HOOKUP_OBJECT (win_gconex, label30, "label30");
  GLADE_HOOKUP_OBJECT (win_gconex, entry_database, "entry_database");
  GLADE_HOOKUP_OBJECT (win_gconex, combo_supp, "combo_supp");
  GLADE_HOOKUP_OBJECT (win_gconex, combo_entry_supp, "combo_entry_supp");
  GLADE_HOOKUP_OBJECT (win_gconex, combo_charger, "combo_charger");
  GLADE_HOOKUP_OBJECT (win_gconex, combo_entry_charger, "combo_entry_charger");
  GLADE_HOOKUP_OBJECT (win_gconex, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (win_gconex, combo_entry1, "combo_entry1");
  GLADE_HOOKUP_OBJECT (win_gconex, bt_exporter, "bt_exporter");
  GLADE_HOOKUP_OBJECT (win_gconex, label36, "label36");
  GLADE_HOOKUP_OBJECT (win_gconex, bt_importer, "bt_importer");
  GLADE_HOOKUP_OBJECT (win_gconex, label37, "label37");
  GLADE_HOOKUP_OBJECT (win_gconex, combo2, "combo2");
  GLADE_HOOKUP_OBJECT (win_gconex, combo_entry2, "combo_entry2");
  GLADE_HOOKUP_OBJECT (win_gconex, label29, "label29");
  GLADE_HOOKUP_OBJECT (win_gconex, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (win_gconex, bt_cancel_win_gconnex, "bt_cancel_win_gconnex");

  return win_gconex;
}

GtkWidget*
create_win_champ (void)
{
  GtkWidget *win_champ;
  GtkWidget *ntbk_champ;
  GtkWidget *vbox14;
  GtkWidget *scrolledwindow15;
  GtkWidget *tv_champ;
  GtkWidget *label34;
  GtkWidget *scrolledwindow20;
  GtkWidget *tv_pile;
  GtkWidget *label35;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  win_champ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (win_champ, 150, 350);
  gtk_tooltips_set_tip (tooltips, win_champ, _("Affiche l'ID de la derni\303\250re cellule s\303\251lectionn\303\251e"), NULL);
  gtk_window_set_title (GTK_WINDOW (win_champ), _("Montreur de champs"));
  gtk_window_set_position (GTK_WINDOW (win_champ), GTK_WIN_POS_CENTER);

  ntbk_champ = gtk_notebook_new ();
  gtk_widget_show (ntbk_champ);
  gtk_container_add (GTK_CONTAINER (win_champ), ntbk_champ);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (ntbk_champ), TRUE);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox14);
  gtk_container_add (GTK_CONTAINER (ntbk_champ), vbox14);

  scrolledwindow15 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow15);
  gtk_box_pack_start (GTK_BOX (vbox14), scrolledwindow15, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow15), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  tv_champ = gtk_tree_view_new ();
  gtk_widget_show (tv_champ);
  gtk_container_add (GTK_CONTAINER (scrolledwindow15), tv_champ);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (tv_champ), TRUE);

  label34 = gtk_label_new (_("Carte"));
  gtk_widget_show (label34);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (ntbk_champ), gtk_notebook_get_nth_page (GTK_NOTEBOOK (ntbk_champ), 0), label34);

  scrolledwindow20 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow20);
  gtk_container_add (GTK_CONTAINER (ntbk_champ), scrolledwindow20);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow20), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  tv_pile = gtk_tree_view_new ();
  gtk_widget_show (tv_pile);
  gtk_container_add (GTK_CONTAINER (scrolledwindow20), tv_pile);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (tv_pile), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (tv_pile), TRUE);

  label35 = gtk_label_new (_("Pile"));
  gtk_widget_show (label35);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (ntbk_champ), gtk_notebook_get_nth_page (GTK_NOTEBOOK (ntbk_champ), 1), label35);

  g_signal_connect ((gpointer) win_champ, "destroy_event",
                    G_CALLBACK (on_win_champ_destroy_event),
                    NULL);
  g_signal_connect ((gpointer) win_champ, "delete_event",
                    G_CALLBACK (on_win_champ_delete_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_champ, win_champ, "win_champ");
  GLADE_HOOKUP_OBJECT (win_champ, ntbk_champ, "ntbk_champ");
  GLADE_HOOKUP_OBJECT (win_champ, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (win_champ, scrolledwindow15, "scrolledwindow15");
  GLADE_HOOKUP_OBJECT (win_champ, tv_champ, "tv_champ");
  GLADE_HOOKUP_OBJECT (win_champ, label34, "label34");
  GLADE_HOOKUP_OBJECT (win_champ, scrolledwindow20, "scrolledwindow20");
  GLADE_HOOKUP_OBJECT (win_champ, tv_pile, "tv_pile");
  GLADE_HOOKUP_OBJECT (win_champ, label35, "label35");
  GLADE_HOOKUP_OBJECT_NO_REF (win_champ, tooltips, "tooltips");

  return win_champ;
}

GtkWidget*
create_win_couleur (void)
{
  GtkWidget *win_couleur;
  GtkWidget *bt_couleur_ok;
  GtkWidget *bt_couleur_cancel;
  GtkWidget *help_button1;
  GtkWidget *color_selection;

  win_couleur = gtk_color_selection_dialog_new (_("Select Color"));
  gtk_window_set_position (GTK_WINDOW (win_couleur), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (win_couleur), FALSE);

  bt_couleur_ok = GTK_COLOR_SELECTION_DIALOG (win_couleur)->ok_button;
  gtk_widget_show (bt_couleur_ok);
  GTK_WIDGET_SET_FLAGS (bt_couleur_ok, GTK_CAN_DEFAULT);

  bt_couleur_cancel = GTK_COLOR_SELECTION_DIALOG (win_couleur)->cancel_button;
  gtk_widget_show (bt_couleur_cancel);
  GTK_WIDGET_SET_FLAGS (bt_couleur_cancel, GTK_CAN_DEFAULT);

  help_button1 = GTK_COLOR_SELECTION_DIALOG (win_couleur)->help_button;
  gtk_widget_show (help_button1);
  GTK_WIDGET_SET_FLAGS (help_button1, GTK_CAN_DEFAULT);

  color_selection = GTK_COLOR_SELECTION_DIALOG (win_couleur)->colorsel;
  gtk_widget_show (color_selection);
  gtk_color_selection_set_has_opacity_control (GTK_COLOR_SELECTION (color_selection), TRUE);
  gtk_color_selection_set_has_palette (GTK_COLOR_SELECTION (color_selection), TRUE);

  g_signal_connect ((gpointer) win_couleur, "destroy_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);
  g_signal_connect ((gpointer) win_couleur, "delete_event",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);
  g_signal_connect ((gpointer) bt_couleur_ok, "clicked",
                    G_CALLBACK (on_slct_couleur_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) bt_couleur_cancel, "clicked",
                    G_CALLBACK (on_slct_couleur_cancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_couleur, win_couleur, "win_couleur");
  GLADE_HOOKUP_OBJECT_NO_REF (win_couleur, bt_couleur_ok, "bt_couleur_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (win_couleur, bt_couleur_cancel, "bt_couleur_cancel");
  GLADE_HOOKUP_OBJECT_NO_REF (win_couleur, help_button1, "help_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (win_couleur, color_selection, "color_selection");

  return win_couleur;
}

GtkWidget*
create_fs_exporter (void)
{
  GtkWidget *fs_exporter;
  GtkWidget *bt_exporter_ok;
  GtkWidget *cancel_button1;

  fs_exporter = gtk_file_selection_new (_("Exporter XML"));
  gtk_container_set_border_width (GTK_CONTAINER (fs_exporter), 10);

  bt_exporter_ok = GTK_FILE_SELECTION (fs_exporter)->ok_button;
  gtk_widget_show (bt_exporter_ok);
  GTK_WIDGET_SET_FLAGS (bt_exporter_ok, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (fs_exporter)->cancel_button;
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) bt_exporter_ok, "clicked",
                    G_CALLBACK (on_bt_exporter_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button1, "clicked",
                    G_CALLBACK (on_cancel_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fs_exporter, fs_exporter, "fs_exporter");
  GLADE_HOOKUP_OBJECT_NO_REF (fs_exporter, bt_exporter_ok, "bt_exporter_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (fs_exporter, cancel_button1, "cancel_button1");

  return fs_exporter;
}

GtkWidget*
create_fs_importer (void)
{
  GtkWidget *fs_importer;
  GtkWidget *bt_importer_ok;
  GtkWidget *cancel_button2;

  fs_importer = gtk_file_selection_new (_("Importer XML"));
  gtk_container_set_border_width (GTK_CONTAINER (fs_importer), 10);

  bt_importer_ok = GTK_FILE_SELECTION (fs_importer)->ok_button;
  gtk_widget_show (bt_importer_ok);
  GTK_WIDGET_SET_FLAGS (bt_importer_ok, GTK_CAN_DEFAULT);

  cancel_button2 = GTK_FILE_SELECTION (fs_importer)->cancel_button;
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) bt_importer_ok, "clicked",
                    G_CALLBACK (on_bt_importer_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) cancel_button2, "clicked",
                    G_CALLBACK (on_cancel_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fs_importer, fs_importer, "fs_importer");
  GLADE_HOOKUP_OBJECT_NO_REF (fs_importer, bt_importer_ok, "bt_importer_ok");
  GLADE_HOOKUP_OBJECT_NO_REF (fs_importer, cancel_button2, "cancel_button2");

  return fs_importer;
}

