/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_win_main (void);
GtkWidget* create_win_about (void);
GtkWidget* create_win_quitte (void);
GtkWidget* create_win_open (void);
GtkWidget* create_win_save (void);
GtkWidget* create_win_RAZ (void);
GtkWidget* create_win_gconex (void);
GtkWidget* create_win_champ (void);
GtkWidget* create_win_couleur (void);
GtkWidget* create_fs_exporter (void);
GtkWidget* create_fs_importer (void);
